project:
  type: book
  output-dir: docs

book:
  title: "1期ゼミ資料"
  author: 
  - name: "佐久間 智広"
    affiliation: "Kobe University"
    email: "sakuma@port.kobe-u.ac.jp"
  date: last-modified
  date-format: YYYY/MM/DD
  chapters:
    - index.qmd
    - intro_text.qmd
    - 2_分析環境の構築_text.qmd
    - ch3.qmd
    - ch4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [yeti, fonts.scss]
    toc: true
    toc-location: left
    toc-title: Contents
    number-sections: true
    number-depth: 3
    title-block-banner: true
    logo: kobe.png
    embed-resources: true
    df-print: paged
  
editor: visual

