project:
  type: book
  output-dir: docs

book:
  title: "1期ゼミ資料"
  author: 
  - name: "佐久間 智広"
    affiliation: "Kobe University"
    email: "sakuma@port.kobe-u.ac.jp"
  date: last-modified
  date-format: YYYY/MM/DD
  chapters:
    - index.qmd
    - intro_text.qmd
    - 2_分析環境の構築_text.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/the-accounting-review
format:
  html:
    theme: [yeti, fonts.scss]
    toc: true
    toc-location: left
    toc-title: Contents
    number-sections: true
    number-depth: 3
    title-block-banner: true
    logo: kobe.png
    embed-resources: true
    df-print: paged
    code-annotations: hover
    code-tools:
      source: false
      toggle: false
      caption: none
    code-fold: show
    code-summary: "Code"
  revealjs:
    width: 1920  #1280
    height: 1080 #1024
    slide-number: true
    preview-links: auto
    logo: kobe.png
    css: logo.css
    footer: "ゼミ"
    smaller: false
    scrollable: true
    theme: [white,fonts.scss]
    fig-cap-location: bottom
    tbl-cap-location: top
    embed-resources: false
    number-sections: false
    chalkboard: true
    number-depth: 2
    toc: true
    toc-depth: 1
    navigation-mode: vertical
    df-print: paged  
    output-file: revealjs.html
    echo: true  
    code-tools:
      source: false
      toggle: false
      caption: none
    code-fold: show
    code-summary: "Show the code"

editor: visual

